http5204-blog-aspcore/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_blog_aspcore.Models;
using http5204_blog_aspcore.Models.ViewModels;
using http5204_blog_aspcore.Data;
using System.Diagnostics;

namespace http5204_blog_aspcore.Controllers
{
    public class BlogController : Controller
    {
        //makes a BlogCMSContext
        private readonly BlogCMSContext db;
        //constructor function which takes a BlogCMSContext as a constructor.
        //Q: How does the Controller just *get* this context?
        //A: "magic" called dependency injection will put the data there.
        
        //We need the usermanager class to get things like the id or name
        //Right now we only have one user type (ApplicationUser) but we could have others.
        private readonly UserManager<ApplicationUser> _userManager;
        //This function will return the current user at some point when called
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);


        public BlogController(BlogCMSContext context, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _userManager = usermanager;
        }
        /*
           Reading links to fully understand this file
           -------------------------------------------
            I don't really understand how Model, View, Controller works
            https://www.tomdalling.com/blog/software-design/model-view-controller-explained/
            https://medium.freecodecamp.org/model-view-controller-mvc-explained-through-ordering-drinks-at-the-bar-efcba6255053
            
            EF Core + ASP Core tutorial
            https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2

            EF Core + ASP Core tutorial 2
            https://www.learnentityframeworkcore.com/walkthroughs/aspnetcore-application

            How can I get Entity Framework Core?
            https://www.learnentityframeworkcore.com/efcore/how-to-get

            How can I use the fancy Entity Framework Core commands? (add, edit, delete)
            https://www.learnentityframeworkcore.com/dbset

            How can I do more advanced commands? (join, where, find)
            https://www.learnentityframeworkcore.com/dbset/querying-data

            I just want to write my own query, How can I do that?
            https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

            How can I know more about parameterized queries?
            https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

            What is this "db" variable?
            https://www.learnentityframeworkcore.com/dbcontext


        */
        
        //This function asks important questions from the user
        //It was built for a need to understand more information about a particular user
        //given a context.
        public async Task<int> GetUserDetails(ApplicationUser user)
        {
            //check if the user is an author or not.
            //UserState
            //0 => No User
            //1 => has user has no author
            //2 => has user has author but no blogs
            //3 => has user has author and at least 1 blog
            if (user == null) return 0;
            var userid = user.Id;
            if (user.AuthorID == null) return 1; //User has no author
            else
            {
                var uauthorid = user.AuthorID;
                var userblogs = await db.Blogs.Where(b => b.AuthorID == uauthorid).ToListAsync();
                var userblogcount = userblogs.Count();
                if (userblogcount == 0) return 2;//User has no blogs
                else if (userblogcount > 0) return 3;
            }
            return -1;//something went wrong
        }

        public async Task<bool> IsUserBlogOwner(ApplicationUser user, int BlogID)
        {
            if (user == null) return false;
            if (user.AuthorID == null) return false;
            //purpose of this function is to check whether the user is the author of the blog
            var userblogs = await
                db
                .Blogs
                .Include(b => b.Author)
                .Where(b => b.AuthorID == user.AuthorID)
                .Where(b => b.BlogID == BlogID)
                .ToListAsync();
            if (userblogs.Count() > 0) return true;
            return false;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public async Task<ActionResult> List(int pagenum)
        {
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            //tell give us context about the user
            ViewData["UserState"] = userstate;
            ViewData["UserAuthorID"] = 0; //default 0
            if (userstate == 3)
            {
                ViewData["UserAuthorID"] = (int)user.AuthorID;
            }

            /*BLOG PAGINATION ALGORITHM*/
            var _blogs = await db.Blogs.Include(b => b.Author).ToListAsync();
            int blogcount = _blogs.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)blogcount/perpage)-1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage+1).ToString();
            }
            //DATA NEEDED: All Blogs in DB
            //However, we also have to include the info for the author on each blog
            //[List<Blog> blogs]=> variable named blogs which is a list of Blog
            //[.Include(b=>b.Author)]=> Get the blog's associated author
            //[.ToListAsync()]=>Return a list of information asynchronously

            //[.Skip(int)]=>ignore these many records
            //[.Take(int)]=>fetch only this many more
            List<Blog> blogs = await db.Blogs.Include(b=>b.Author).Skip(start).Take(perpage).ToListAsync();
            /*END OF BLLOG PAGINATION ALGORITHM*/
            return View(blogs);

            
            
        }

        public async Task<ActionResult> New()
        {
            //DATA NEEDED
            //we need to know the context of the user
            //are they registered as an author?
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            //userstate gets the context of the user
            switch (userstate)
            {
                case 0: return RedirectToAction("Register","Account");
                case 1: return RedirectToAction("Create","Author");
            }
            //The user should have an author if not 0 or 1
            ViewData["UserAuthorID"] = user.AuthorID;
            //Model defined in Models/ViewModels/BlogEdit.cs
            BlogEdit blogeditview = new BlogEdit();

            //GOTO Views/Blog/New.cshtml
            return View(blogeditview);
        }

        [HttpPost]
        public async Task<ActionResult> Create(string BlogTitle_New, int BlogAuthor_New, string BlogBio_New)
        {
            //need to check if the author is indeed who they say they are.
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

            //Can't make a blog if you aren't an author or don't have an account
            if (userstate < 2) return Forbid();
            if (user.AuthorID != BlogAuthor_New)
            {
                //someone tried to impersonate a blog user by switching the hidden field ID
                return Forbid();
            }

            //Raw Query   
            string query = "insert into blogs (BlogTitle, BlogBio, AuthorID) values (@title, @bio, @author)";

            //SQL parameterized query technique
            //[SqlParameter[] myparams] => SET variable myparams as an array of type (SqlParameter)
            //[new SqlParameter[1]] => Create a new SqlParameter array with 3 items
            SqlParameter[] myparams = new SqlParameter[3];
            //@title paramter
            myparams[0] = new SqlParameter("@title", BlogTitle_New);
            //@bio parameter
            myparams[1] = new SqlParameter("@bio", BlogBio_New);
            //@author (id) FOREIGN KEY paramter
            myparams[2] = new SqlParameter("@author", BlogAuthor_New);
            
            //Run the parameterized query (DML - Data Manipulation Language)
            //Insert into blogs ( .. ) values ( .. ) 
            db.Database.ExecuteSqlCommand(query, myparams);

            //GOTO: 
            return RedirectToAction("List");
        }

        public async Task<ActionResult> Edit(int id)
        {
            //Data Needed:
            //One particular blog (we have the id)
            //That blogs' author
            //The user's author

            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            bool isValid = await IsUserBlogOwner(user, id);
            if (!isValid) return Forbid();


            var myblog = db.Blogs.Find(id); //finds that blog
            if (myblog != null) return View(myblog);
            else return NotFound();   
        }

        [HttpPost]

http5204-blog-aspcore/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using http5204_blog_aspcore.Models;
using http5204_blog_aspcore.Data;

namespace http5204_blog_aspcore.Controllers
{
    public class TagController : Controller
    {
        //makes a BlogCMSContext
        private readonly BlogCMSContext db;
        //constructor function which takes a BlogCMSContext as a constructor.
        //Q: How does the Controller just *get* this context?
        //A: "magic" called dependency injection will put the data there.
        public TagController(BlogCMSContext context)
        {
            db = context;
        }
        /*
           Reading links to fully understand this file
           -------------------------------------------
            I don't really understand how Model, View, Controller works
            https://www.tomdalling.com/blog/software-design/model-view-controller-explained/
            https://medium.freecodecamp.org/model-view-controller-mvc-explained-through-ordering-drinks-at-the-bar-efcba6255053
            
            EF Core + ASP Core tutorial
            https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2

            EF Core + ASP Core tutorial 2
            https://www.learnentityframeworkcore.com/walkthroughs/aspnetcore-application

            How can I get Entity Framework Core?
            https://www.learnentityframeworkcore.com/efcore/how-to-get

            How can I use the fancy Entity Framework Core commands? (add, edit, delete)
            https://www.learnentityframeworkcore.com/dbset

            How can I do more advanced commands? (join, where, find)
            https://www.learnentityframeworkcore.com/dbset/querying-data

            I just want to write my own query, How can I do that?
            https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

            How can I know more about parameterized queries?
            https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

            What is this "db" variable?
            https://www.learnentityframeworkcore.com/dbcontext


        */

        // GET: Tag
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            /*
            Alternate
            IEnumerable<Tag> tags = db.Tags.ToList();
            */

            string query = "select * from Tags";
            
            IEnumerable<Tag> tags = db.Tags.FromSql(query);
            
            return View(tags);
        }

        public ActionResult New()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(string TagName_New, string TagColor_New)
        {
            string query = "insert into tags (TagName, TagColor)" +
                " values (@name, @color)";
            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@name", TagName_New);
            myparams[1] = new SqlParameter("@color", TagColor_New);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }

        //TODO: EDIT VIEW, EDIT, DELETE, SHOW

        public ActionResult Edit(int? id)
        {
            if ((id == null) || (db.Tags.Find(id) == null))
            {
                return NotFound();
            }
            string query = "select * from Tags where tagid=@id";
            SqlParameter param = new SqlParameter("@id",id);
            Tag mytag = db.Tags.FromSql(query, param).FirstOrDefault();
            return View(mytag);
        }

        [HttpPost]
        public ActionResult Edit(int? id, string TagName, string TagColor)
        {
            if ((id == null) || (db.Tags.Find(id) == null)){
                return NotFound();
            }
            string query = "update tags set TagName=@name, TagColor=@color" +
                " where tagid=@id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@name",TagName);
            myparams[1] = new SqlParameter("@color",TagColor);
            myparams[2] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Show/" + id);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if ((id==null)||(db.Tags.Find(id)==null))
            {
                return NotFound();

            }
            string query = "delete from tags where tagid=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query,param);
            return View("List");
        }

        public ActionResult Show(int? id)
        {
            if ((id == null) || (db.Tags.Find(id) == null))
            {
                return NotFound();

            }
            string query = "select * from Tags where tagid=@id";
            SqlParameter param = new SqlParameter("@id",id);

            Tag tagtoshow = db.Tags.Include(t=>t.pagesxtags).ThenInclude(pxt=>pxt.Page).SingleOrDefault(t=>t.TagID==id);

            return View(tagtoshow);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

http5204-blog-aspcore/Views/Page/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

http5204-blog-aspcore/Views/Page/Edit.cshtml
@model http5204_blog_aspcore.Models.ViewModels.PageEdit
@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Model.Page.PageTitle</h2>

<form method="POST" action="/Page/Edit/@Model.Page.PageID">
    <div class="inprow">
        <label class="inplabel">Title</label>
        <input type="text" value="@Model.Page.PageTitle" id="PageTitle" name="PageTitle" />
    </div>
    <div class="inprow">
        <div class="inplabel">Blog</div>
        <select id="PageBlog" name="PageBlog">
            @foreach(var Blog in Model.Blogs)
            {
                string current = "false";
                @if(Blog.BlogID == Model.Page.Blog.BlogID)
                {
                    current = "true";
                }
                
                <option value="@Blog.BlogID" selected="@current">@Blog.BlogTitle</option>
            }

        </select>
    </div>
    <div class="inprow" id="colortags">
        <div class="inplabel">Page Tags:</div>
        @foreach (var Tag in Model.Tags)
        { //Loops through all tags in the database
            string selected = "";
            string neg_selected = "checked";
            //Check to see if any of these tags are applied to this page
            if (Model.Page.pagesxtags.Exists(pxt=>pxt.Tag==Tag))
            {
                selected = "checked";
                neg_selected = "";
                //html attribute on a checkbox for default check
            }
            <label>
                
                <input type="checkbox"
                       name="PageTags"
                       value="@Tag.TagID" 
                       @selected
                       onchange="var val = (this.checked) ? false : true; document.getElementById('Removed_PageTag_'+@Tag.TagID).checked=val;"/>
                @Tag.TagName
            </label>

            <!-- The natural HTML checkbox interface is a little skimpy
                so here's a bit
                of a clever trick for REMOVING tags from pages.
                build a "negative" checkbox list, so that when items are unchecked,
                we send a second list of items to remove.
                comment out the display:none; to see visually of how it works
                -->
            <label style="display:none;">
                @Tag.TagName
                <input 
                       type="checkbox" 
                       name="Removed_PageTags" 
                       id="Removed_PageTag_@Tag.TagID" 
                       value="@Tag.TagID"
                       @neg_selected/>
            </label>
        }
    </div>
    <div class="inprow">
        <div class="inplabel">Content</div>
        <textarea id="PageContent" name="PageContent">@Model.Page.PageContent</textarea>
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>

http5204-blog-aspcore/Views/Page/List.cshtml
@model IEnumerable<http5204_blog_aspcore.Models.Page>
@{


    ViewBag.Title = "List";
}

<div class="banner" id="pagebanner">
    <h2>Pages</h2>
</div>
<div class="recadd">
    @{
        //User Switching Logic
        //UserState
        //0 => No User
        //1 => has user has no author
        //2 => has user has author but no blogs
        //3 => has user has author and at least 1 blog
        switch (ViewData["UserState"]) {
            case 0: { @Html.ActionLink("Register An Account", "Register", "Account"); break; }
            case 1: { @Html.ActionLink("Become a Writer!", "Create", "Author"); break; }
            case 2: { @Html.ActionLink("Tell Your Story.", "New","Blog"); break; }
            case 3: { @Html.ActionLink("Write a Page!", "New", "Page");break; }


        }
    }
</div>
<div class="reccontainer">
<div id="paginate">
    @ViewData["PaginationSummary"]
    @Html.ActionLink("Prev",
        "List",
        "Page",
        new { pagenum = ((int)ViewData["pagenum"] - 1) }
        )
    |
    @Html.ActionLink("Next",
        "List",
        "Page",
        new { pagenum = ((int)ViewData["pagenum"] + 1) }
    )
</div>
@foreach (var Page in Model)
        {

    <div class="rec">
        
        <div class="recprofile">
            <div class="img-container">
                @if (Page.Blog.Author.HasPic == 1)
                {
                    <img src="~/images/authors/@(Page.Blog.Author.AuthorID).@(Page.Blog.Author.ImgType)" />
                }
                else
                {
                    <img src="~/images/authors/default.jpg" />
                }
            </div>
            <span class="img-caption">@Page.Blog.Author.AuthorPenName</span>
        </div>
        <div class="recbody">
            <label>@Html.ActionLink(Page.PageTitle, "Show", "Page", new { id = Page.PageID })</label>
            <label id="authorname_subhead">By @Page.Blog.Author.AuthorPenName</label>
            <div style="overflow:hidden;">
                @foreach (var pxt in Page.pagesxtags)
                {
                    <span style="background:#@pxt.Tag.TagColor; margin-bottom:5px;" class="colorbox">@Html.ActionLink(pxt.Tag.TagName, "Show/"+pxt.Tag.TagID, "Tag")</span>

                }
            </div>
            <p>@Page.PageContent</p>
            <span class="del">
                <a href="@Url.Action("Delete/"+Page.PageID)"><i class="far fa-trash-alt"></i></a>
            </span>
        </div>
        <div class="clearfix"></div>
    </div>
    
}
</div>

http5204-blog-aspcore/Views/Page/New.cshtml
@model IEnumerable<http5204_blog_aspcore.Models.Blog>
@{
    ViewBag.Title = "New";
}

<h2>New Page</h2>
<form method="POST" action="/Page/Create">
    <div class="inprow">
        <label class="inplabel">Title</label>
        <input id="PageTitle_New" name="PageTitle_New" />
    </div>
    <div class="inptrow">
        <label class="inplabel">Blog</label>
        <select id="PageBlog_New" name="PageBlog_New">
            @foreach (var blog in Model)
            {
                <option value="@blog.BlogID">@blog.BlogTitle</option>
            }
        </select>
    </div>
    <div class="inprow">
        <div class="inplabel">Content</div>
        <textarea  id="PageContent_New" name="PageContent_New"></textarea>
    </div>
    <div class="inprow">
        <input type="submit" value="Submit"/>
    </div>
</form>

http5204-blog-aspcore/Views/Page/Show.cshtml
@model http5204_blog_aspcore.Models.Page
@{
    ViewBag.Title = "Show";
}

<h2>@Model.PageTitle</h2>
<div style="overflow:hidden;">
    @foreach (var pxt in Model.pagesxtags)
    {
        <span style="background:#@pxt.Tag.TagColor" class="colorbox">@Html.ActionLink(pxt.Tag.TagName, "Show/" + pxt.Tag.TagID, "Tag")</span>

    }
</div>
<div class="promptlink">
    @{ 
        if ((bool)ViewData["IsUserPageOwner"])
        {
            @Html.ActionLink("Edit your Page","Edit","Page", new {id=Model.PageID});
        }
    }
</div>
<div>
    <div class="pagecolumn">
        <article class="pagecontent">
            <p>@Model.PageContent</p>
        </article>
    </div>
    <div class="authorcolumn">
        <aside class="img-container">
            @{
                string imgpath = "";
            }
            @if (Model.Blog.Author.HasPic == 1)
            {
                <img src="~/images/authors/@(Model.Blog.Author.AuthorID).@(Model.Blog.Author.ImgType)" />
            }
            else
            {
                <img src="~/images/authors/default.jpg" />
            }
            
        </aside>
        <span>Written By: @Html.ActionLink(Model.Blog.Author.AuthorPenName,"Details/"+Model.Blog.Author.AuthorID,"Author")</span>
    </div>
    <div class="clearfix"></div>
</div>